name: Nightly

on:
  push:
    branches: [ add-nightly-test ]
#  schedule:
#    - cron: 0 4 * * 1-5

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      #- name: Build
      #  run: go build -v ./...

      #- name: Test
      #  run: go test -v ./...

      - name: Build
        run: make release-local

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create cluster
        run: |
          cat <<EOF | dist/default_linux_amd64/okctl apply cluster -g token -a access-key -q -f -
            kind: Cluster
            apiVersion: okctl.io/v1alpha1
            metadata:
              accountID: "932360772598"
              environment: test
              name: nightly
              region: eu-west-1
            primaryDNSZone:
              managedZone: false
              parentDomain: nightly-test.oslo.systems
            github:
              organisation: oslokommune
              outputPath: infrastructure
              repository: julius_iac
              team: kjoremiljo
            integrations:
              argoCD: true
              awsLoadBalancerController: true
              cognito: true
              externalDNS: true
              externalSecrets: true
            vpc:
              cidr: 192.168.0.0/20
              highAvailability: true
          EOF
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Delete cluster
        run: dist/default_linux_amd64/okctl delete cluster -g token -a access-key -q test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
